"""Score frozen model versions on a labelled eval set (e.g. a fresh hand-written one).

Nothing is trained or tuned here. For the urgency model, the weak-supervision rules are
scored too, since a model trained on them has to beat them to be worth serving.

The eval CSV needs a `text` column plus the label column for the model (`category` or
`urgency`). Rows with an empty label are skipped, so one file can hold both.

Usage (from backend/):
    uv run python -m scripts.evaluate_model --model urgency_classifier --versions v1 v2 \\
        --eval-set ../data/eval/urgency_holdout_test.csv

Writes app/ml/artifacts/<model>/eval_<eval-set name>.md and prints the summary.
"""

import argparse
from pathlib import Path

import pandas as pd

from app.core.enums import ModelName, TicketCategory, TicketUrgency
from app.ml.store import ARTIFACTS_DIR, load_bundle
from app.ml.weak_labels import weak_label
from scripts.ml_training import evaluate, file_sha256, md_confidence, md_confusion, md_errors, md_per_class, md_summary

LABEL_COLUMN = {ModelName.CATEGORY_CLASSIFIER: "category", ModelName.URGENCY_CLASSIFIER: "urgency"}
CLASSES = {
    ModelName.CATEGORY_CLASSIFIER: [str(c) for c in TicketCategory],
    ModelName.URGENCY_CLASSIFIER: [str(u) for u in TicketUrgency],
}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--model", type=ModelName, choices=list(ModelName), required=True)
    parser.add_argument("--versions", nargs="+", required=True)
    parser.add_argument("--eval-set", type=Path, required=True)
    args = parser.parse_args()

    column, classes = LABEL_COLUMN[args.model], CLASSES[args.model]
    df = pd.read_csv(args.eval_set)
    df = df[df[column].notna() & (df[column].astype(str).str.strip() != "")].reset_index(drop=True)
    df[column] = df[column].str.strip().str.lower()
    if bad := set(df[column]) - set(classes):
        raise SystemExit(f"Unknown {column} labels in {args.eval_set}: {sorted(bad)}")
    if df.empty:
        raise SystemExit(f"No rows with a {column} label in {args.eval_set}")
    texts, y_true = df["text"].tolist(), df[column].tolist()

    results, sections = {}, []
    for version in args.versions:
        bundle = load_bundle(args.model, version)
        y_pred, conf = bundle.predict_many(texts)
        result = evaluate(y_true, y_pred, classes, conf)
        results[version] = {"eval": result}
        sections.append(
            f"## {version}\n\n{md_per_class(result)}\n\n{md_confusion(result, classes)}\n\n"
            f"{md_confidence({args.eval_set.name: result})}\n\n### Errors\n\n{md_errors(texts, y_true, y_pred, conf, limit=60)}"
        )
    if args.model is ModelName.URGENCY_CLASSIFIER:
        rules = evaluate(y_true, [str(weak_label(t).label) for t in texts], classes)
        results["rules alone"] = {"eval": rules}
        sections.append(f"## Rules alone\n\n{md_per_class(rules)}\n\n{md_confusion(rules, classes)}")

    summary = md_summary(results)
    report = (
        f"# {args.model}: evaluation on `{args.eval_set.name}`\n\n"
        f"{len(df)} labelled rows, sha256 `{file_sha256(args.eval_set)[:12]}`. Generated by `scripts/evaluate_model.py`.\n\n"
        f"{summary}\n\n" + "\n\n".join(sections) + "\n"
    )
    out = ARTIFACTS_DIR / args.model / f"eval_{args.eval_set.stem}.md"
    out.write_text(report)
    print(summary)
    print(f"\nSaved to {out}")


if __name__ == "__main__":
    main()
