"""Check that knowledge-base search returns entries relevant to real tickets.

Queries are the 120 hand-written tickets (data/eval/handwritten_test_set.csv), each with a
human category label. An entry counts as relevant if data/knowledge_base.json tags it with
the ticket's category. Reported per category:
- hit@1 / hit@3: share of tickets with a relevant entry at rank 1 / in the top 3
  (the Knowledge Agent passes the top 3 to the Draft Agent)
- MRR: mean of 1/rank of the first relevant entry

Category-level relevance is coarse: it says the right *kind* of policy came back, not the
single best entry. The same author wrote the tickets and the knowledge base, so treat it
as a sanity check. Reads the knowledge base from the database: run seed_knowledge_base first.

Usage (from backend/):
    uv run python -m scripts.evaluate_retrieval --tenant dev
"""

import argparse
import asyncio
import json
from collections import defaultdict

import pandas as pd

from app.core.admin_db import admin_tenant_session
from app.ml.store import ARTIFACTS_DIR
from app.services.knowledge_base import search
from scripts.ml_training import HANDWRITTEN_PATH
from scripts.seed_knowledge_base import KB_PATH

K = 3
REPORT_PATH = ARTIFACTS_DIR / "knowledge_base" / "retrieval_eval.md"


async def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--tenant", default="dev", help="tenant whose knowledge base holds data/knowledge_base.json")
    args = parser.parse_args()
    tickets = pd.read_csv(HANDWRITTEN_PATH)
    tags = {e["title"]: set(e["categories"]) for e in json.loads(KB_PATH.read_text())}

    per_category: dict[str, list[tuple[bool, bool, float]]] = defaultdict(list)
    misses = []
    async with admin_tenant_session(args.tenant) as session:
        for text, category in zip(tickets["text"], tickets["category"], strict=True):
            docs = await search(session, text, k=K)
            ranks = [i for i, d in enumerate(docs, 1) if category in tags.get(d.title, set())]
            first = ranks[0] if ranks else None
            per_category[category].append((first == 1, first is not None, 1 / first if first else 0.0))
            if first is None:
                misses.append((category, text, [d.title for d in docs]))

    rows = []
    for category, results in [*sorted(per_category.items()), ("**all**", [r for rs in per_category.values() for r in rs])]:
        n = len(results)
        rows.append(
            f"| {category} | {n} | {sum(r[0] for r in results) / n:.2f} | {sum(r[1] for r in results) / n:.2f} "
            f"| {sum(r[2] for r in results) / n:.2f} |"
        )
    miss_lines = [f"- **{c}**: {t[:120]}… → {', '.join(titles)}" for c, t, titles in misses] or ["_None._"]
    report = "\n".join(
        [
            "# Knowledge-base retrieval check",
            "",
            f"{len(tickets)} hand-written tickets as queries against {len(tags)} entries; relevant = entry tagged "
            f"with the ticket's category. Generated by `scripts/evaluate_retrieval.py`.",
            "",
            f"| category | tickets | hit@1 | hit@{K} | MRR |",
            "|---|---|---|---|---|",
            *rows,
            "",
            f"## Tickets with no relevant entry in the top {K}",
            "",
            *miss_lines,
            "",
        ]
    )
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(report)
    print("\n".join(report.splitlines()[4 : 7 + len(rows)]))
    print(f"\n{len(misses)} misses; report saved to {REPORT_PATH}")


if __name__ == "__main__":
    asyncio.run(main())
